### ISSUE TITLE
What are the *_prog files?

### ISSUE THREAD

**Issue by ZhaofengWu** [jkkummerfeld/berkeley-coreference-analyser#3]
I understand that the `*.corrected.$ERROR_TYPE` files are the system output with `$ERROR_TYPE` fixed, but what are the `*_prog` files? And why isn't there one associated with confused entity? Thanks in advance!

**Comment by jkkummerfeld** [comment]
If I remember correctly, `prog` is short for 'progressive'. Rather than fixing the errors independently, it shows fixing all errors of one type, then that type and the next type, and so on. The order is the same as in the paper. The reason there is no file for the confused entity case is that at that point it has reached the gold standard.

**Comment by ZhaofengWu** [comment]
Hi, following up this, I just wanted to check the rationale for the absence of the `_prog` file for the confused entity case. You said it's because after fixing the confused entities the system gets 100%, but actually the confused entity case comes _first_ after span errors, rather than last, in your Table 10. I was thinking if it's missing rather because in the non progressive setting, the fixes are still based on the span error fixes, so since the confused entity fix is the first after span errors, the progressive setting yields the same output as the non progressive setting, both being original output + span error fixes + confused entity fixes. Could you help confirm?

If that were true, though, sometimes the best `_prog` file doesn't get exactly 100% performance, but 99.xx%. Do you have any idea why that could happen?

Thanks for your help!

**Comment by jkkummerfeld** [comment]
You're right, that is the first step. Then the reason there is no separate `_prog` file is that it would be same as the non-`_prog` file. Sorry for the mix-up, it's been a while since I've worked on this code!

As for not getting 100% performance, that's probably because of some edge cases that the application of the corrections doesn't account for. Note that the generation of the `_prog` files is completely separate from the error detection and categorisation. The code takes the output of that process and uses it to then simulate the corrections.

**Comment by ZhaofengWu** [comment]
Thank you!
