### ISSUE TITLE
Request for Active Version

### ISSUE THREAD

**Issue by KawshikManikantan** [jkkummerfeld/berkeley-coreference-analyser#5]
Dear Authors,
This is great work and it would be highly useful for future researchers if this repository is well maintained. Is there any active version of the same repository preferably in Python 3? Really would like to reimplement it but require some help.

Thank you

**Comment by jkkummerfeld** [comment]
Thanks for your interest!

Updating to Python 3 would be good. I am not sure when I will have time to do it, but will put it on my todo list.

**Comment by KawshikManikantan** [comment]
Hello @jkkummerfeld ,
Sorry for the late response on the same thread. I have been instructed to reimplement the repository in Python3. I would be grateful if you could clarify a doubt that I have:

In coreference_reading.py in nlp_utils:

`if "tc/ch/00/ch" in filename and '9' not in filename:
	val = int(filename.split('_')[-1]) * 10 - 1`
	
What is the reasoning behind this special condition? I could notice no discrepancy in the dataset that requires such a change?

**Comment by jkkummerfeld** [comment]
I don't remember exactly what the issue was. The code is changing the filename it gets so my assumption is that there was a mismatch between the predicted and gold files. It's very possible that that was a bug in the CoNLL shared task that has since been fixed or is no longer relevant.

In particular, my memory is that in the shared task the participants received a set of files with the words of the documents, but no annotations. It's possible that those files had a mismatch with the gold files.

**Comment by jkkummerfeld** [comment]
Thank you for working on a Python 3 version!

**Comment by KawshikManikantan** [comment]
Thanks a lot for your quick reply.

**Comment by jkkummerfeld** [comment]
I've updated the code to work with Python3.

**Comment by KawshikManikantan** [comment]
Thanks a lot for this contribution @jkkummerfeld
